# Optional local profile (H2)
# Run with profile: h2
# Example: ./mvnw spring-boot:run -Dspring-boot.run.profiles=h2

spring.datasource.url=jdbc:h2:mem:catalogo_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
